#!/usr/bin/env python3
"""Fetch GoatCounter's count.js, take the two storage lines out, and write it
into assets/js/ so the site serves it itself.

Why self-host at all. The privacy notice says nothing is stored on the
visitor's device and nothing is read from it, on any page. From a CDN that
claim could not be kept: count.js reads `skipgc` in two places, and only one
of them is the filter that analytics.js replaces. The other is top level, in
the `#toggle-goatcounter` branch, and it is reached before any of our code
runs. Somebody using that opt-out would be told by an alert that tracking is
off, have something written to their device, and go on being counted, because
our filter never reads the key. A promise made by a third party that the site
does not keep.

Serving our own copy also removes the last third-party request from the
pages, which is the same policy that already self-hosts the fonts.

What is removed, and nothing else:

  1. `skipgc` inside the default filter. analytics.js replaces that filter
     anyway, so this line is dead in our build — but it has to go for the
     build's storage check to pass, and that check is the thing that keeps
     the privacy notice honest.
  2. The whole `#toggle-goatcounter` block: two reads, a write, a removal and
     two alerts.

Both are the opt-out GoatCounter offers. Ours is Do Not Track and Global
Privacy Control, which are browser settings rather than a URL nobody would
guess, and which need no storage. The privacy notice says so.

The file is licensed ISC, which permits this; the licence header is kept.

Run after a GoatCounter update, and read the diff:

    python3 scripts/vendor_count_js.py

If either block has changed upstream, this stops rather than writing a file
that still touches storage.

Usage: python3 scripts/vendor_count_js.py
"""

import pathlib
import re
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = "https://gc.zgo.at/count.js"
TARGET = ROOT / "assets" / "js" / "count.js"

# Matched exactly, tabs and all. If upstream reformats, the build stops here
# rather than shipping a copy that still reads the device.
FILTER_LINE = (
    "\n\t\tif (localStorage && localStorage.getItem('skipgc') === 't')"
    "\n\t\t\treturn 'disabled with #toggle-goatcounter'"
)
TOGGLE_BLOCK = (
    "\t// Make it easy to skip your own views.\n"
    "\tif (location.hash === '#toggle-goatcounter') {\n"
    "\t\tif (localStorage.getItem('skipgc') === 't') {\n"
    "\t\t\tlocalStorage.removeItem('skipgc', 't')\n"
    "\t\t\talert('GoatCounter tracking is now ENABLED in this browser.')\n"
    "\t\t}\n"
    "\t\telse {\n"
    "\t\t\tlocalStorage.setItem('skipgc', 't')\n"
    "\t\t\talert('GoatCounter tracking is now DISABLED in this browser until "
    "' + location + ' is loaded again.')\n"
    "\t\t}\n"
    "\t}"
)

NOTE = (
    "// Vendored by scripts/vendor_count_js.py from https://gc.zgo.at/count.js\n"
    "// Two things are removed and nothing else: the `skipgc` line in the\n"
    "// default filter, and the whole `#toggle-goatcounter` block. Both read or\n"
    "// write browser storage, and this site's privacy notice says it does\n"
    "// neither. The opt-out here is Do Not Track and Global Privacy Control,\n"
    "// honoured in assets/js/analytics.js. Do not edit this file by hand.\n"
    "//\n"
    "// The words for those storage APIs are kept out of this note on purpose:\n"
    "// the build proves the claim by scanning this file for them, and a\n"
    "// comment would fail that check for the wrong reason.\n"
)


def main():
    with urllib.request.urlopen(SOURCE, timeout=30) as response:
        original = response.read().decode("utf-8")

    for name, block in (("the filter's skipgc line", FILTER_LINE),
                        ("the #toggle-goatcounter block", TOGGLE_BLOCK)):
        if block not in original:
            raise SystemExit(
                f"Stopped: {name} is not where it was in count.js.\n"
                "GoatCounter has changed it, so removing it by hand is no longer\n"
                "safe. Read the new source, update this script, and only then\n"
                "write the file."
            )

    patched = original.replace(FILTER_LINE, "").replace(TOGGLE_BLOCK, "")

    left = sorted(set(re.findall(r"localStorage|sessionStorage|document\.cookie", patched)))
    if left:
        raise SystemExit(
            "Stopped: the patched copy still touches " + ", ".join(left) + ".\n"
            "Something new appeared upstream. Read it before shipping it."
        )

    # The licence header is the first two lines, and it stays first.
    licence, rest = patched.split("\n", 2)[:2], patched.split("\n", 2)[2]
    TARGET.write_text("\n".join(licence) + "\n" + NOTE + rest, encoding="utf-8")

    removed = len(original) - len(patched)
    print(f"Wrote {TARGET.relative_to(ROOT)} ({len(patched)} bytes, {removed} removed).")
    print("No localStorage, no sessionStorage, no cookies.")
    print("Rebuild so the pages point at the local copy.")


if __name__ == "__main__":
    sys.exit(main())
